name: Staging CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate Compose
      run: docker-compose -f docker-compose.yml -f docker-compose.staging.yml up -d --build

    - name: Build Docker Image
      run: docker build -t saleor-dashboard:staging .

    - name: Trivy Scan
      run: trivy image saleor-dashboard:staging

    - name: Push to DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u your-dockerhub-username --password-stdin
        docker push saleor-dashboard:staging
