name: Develop CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: pip install poetry==1.8.4

    - name: Install dependencies with Poetry
      run: poetry install --no-root

    - name: Lint Code
      run: ruff check .
      continue-on-error: true

    - name: Audit Dependencies
      run: pip-audit
      continue-on-error: true

    - name: Build Docker Image
      run: docker build -t saleor-dashboard:develop .

    - name: Trivy Scan
      run: trivy image saleor-dashboard:develop

    - name: Push to DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u your-dockerhub-username --password-stdin
        docker push saleor-dashboard:develop
